DELETE http://localhost:3003/api/blogs/5beb25ce6da7c724ab34306b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjViZTljNzA3MDUxYzdlMzYyZWFiMGRmOCIsImlhdCI6MTU0MjEzNDk3NH0.KxStZMArNtGOPZ_B4cOIv2giNhfna4KcXp5LxaginJI
